env: PlanarDroneSin2x2
n_iter: 10000
batch_size: 2048
adjust_weight: False
u_nominal: None
init_iter: 3000
condition_iter: 250
decent_iter: 750
gpus: 0
log_path: ./logs
seed: 0
no_cuda: False
algo: niss
hyper_params: using default hyper-parameters